### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ludberg** [aalteirac/spotifySessionApp#5]
I followed the readme but got a lot of errors. 

I'm running Qlik Sense Desktop November 2017 Patch 2

What might be the problem?

![errors](https://user-images.githubusercontent.com/3208326/36021560-79e2c812-0d86-11e8-801d-f09c0ce86071.PNG)

**Comment by aalteirac** [comment]
Hi Anders, 
requirejs has been updated in Nov release, that's the reason of the your stack. I've updated it, please let me know if it works.
Tx !

**Comment by ludberg** [comment]
I got past this problem but now I get the following problem

![error2](https://user-images.githubusercontent.com/3208326/36352472-d9168adc-14b9-11e8-90ce-efd1d28889cc.PNG)

The Alert is on line 174 in spotify-session-app.js.

I guess I have problems with my Virtual Proxy. Can you provide a screenshot of ALL the settings in a working Virtual Proxy?

Edit: I'm now trying on the same server where I have the Sense server installed

**Comment by ludberg** [comment]
Should _Session module base URI_ be http://localhost:3002/**main** or http://localhost:3002/**session**

Should I use Authentication method: Ticket?
Should I allow anon loggins?

It doesn't matter how I configure my Virtual Proxy, it gives me a 500 Error when trying to access https://localhost/ano/hub

Any ideas?

**Comment by aalteirac** [comment]
![image](https://user-images.githubusercontent.com/8478296/36354753-76c50122-14d9-11e8-962b-be91a0754cbe.png)

here's the high level flows, yes the session url must be "session". You can first try with desktop, it will will help to spot potential problems and understand the flows. I admit the doc is far for being perfect, apologize :-( I'll post the vp settings asap but need to setup a server first. I''ll give then you answers for the other questions (auth, anonymous).

**Comment by ludberg** [comment]
I did get it working on desktop about a year ago but not I want it running on a server so our sales people can access it. 

It looks like the session-url is not working properly. As soon as I add http://localhost:3002/session to the Integration-park of the Virtual Proxy, I get a 500 Internal Server error. 

Please set it up yourself and post the correct configuration. 


![error3](https://user-images.githubusercontent.com/3208326/36472754-0266535a-16f3-11e8-9f4e-0c86cbd818c3.PNG)

**Comment by aalteirac** [comment]
Hi Anders, here's my vp, the session module was wrong: 

![image](https://user-images.githubusercontent.com/8478296/36478123-eb30b516-1703-11e8-86b7-b4afa725eeaf.png)

![image](https://user-images.githubusercontent.com/8478296/36478081-ca47f7ec-1703-11e8-8278-687f7b11434e.png)

**Comment by ludberg** [comment]
Here's my settings and this doesn't work

The error I get in Chrome
![error4](https://user-images.githubusercontent.com/3208326/36485943-9e934dda-171d-11e8-878d-644a3dbca426.png)

My settings in your script
![errors4](https://user-images.githubusercontent.com/3208326/36485967-aa21c03c-171d-11e8-8270-c0403be70316.PNG)
![errors5](https://user-images.githubusercontent.com/3208326/36485970-ac2862d2-171d-11e8-942c-188aab6b79f4.PNG)

My virtual proxy settings
![virtualproxy1](https://user-images.githubusercontent.com/3208326/36485983-b17dc61e-171d-11e8-8c41-c01d0663910c.PNG)
![virtualproxy2](https://user-images.githubusercontent.com/3208326/36485986-b45cbb38-171d-11e8-9a1f-e298d443945c.PNG)

**Comment by aalteirac** [comment]
Does your proxy allow "http" ?

**Comment by ludberg** [comment]
Yes it does

**Comment by aalteirac** [comment]
oki, that's gonna be difficult to debug. I'll setup another server with Nov release on my side and will try to reproduce. Stay in touch

**Comment by ludberg** [comment]
I'm actually on 2018 Feb and it doesn't work either :(

Thank you for you effort to solve this! It will be very helpful for me

**Comment by aalteirac** [comment]
Hi Anders, 

quick recap: I have Nov release installed and it works fine for me. The error you have shows the /session endpoint of the module is not called. Please double check if the config is correct "X-sess" in vp and config. (looks fine in the screen shot). Check the cookie is created on localhost:3002, in chrome debugger/tab application

**Comment by aalteirac** [comment]
just in case... does your VP linked to the proxy ? and vp tight to central engine ?
![image](https://user-images.githubusercontent.com/8478296/36566698-83b39e18-1824-11e8-88a4-13258c0bdc5a.png)

![image](https://user-images.githubusercontent.com/8478296/36566475-e07bf38a-1823-11e8-82a7-cb8f92969d12.png)

**Comment by aalteirac** [comment]
Also, be sure the url in the front config is the same used to access the mashup site:
![image](https://user-images.githubusercontent.com/8478296/36568634-faac3ace-182a-11e8-8efc-50f066925052.png)
![image](https://user-images.githubusercontent.com/8478296/36568650-115f36d6-182b-11e8-9199-fc809a59edfc.png)

**Comment by ludberg** [comment]
This is driving me mad. 

I can't get past this error!

It doesn't matter if I try 

localhost/ano/resources/js/qlik.js or
192.168.1.143/ano/resources/js/qlik.js or
ex188/ano/resources/js/qlik.js

I can access the qlik.js file if and only if I remove "http://localhost:3002/main" from the **Session Module Base URI**.

Is there any other option somewhere in the QMC I need to change or apply? The Virtual Proxy is Linked to my Proxy Service but not set as default. 

![error7](https://user-images.githubusercontent.com/3208326/36629405-b3655656-1955-11e8-99ae-058fc557630e.png)

**Comment by ludberg** [comment]
If I remove http://localhost:3002/main from the Virtual Proxy I get the following error
`ERROR on createSessionApp Error: Not connected
    at RPC.send (C:\Users\anders.uddenberg\Desktop\spotifySessionApp2\node_modules\enigma.js\dist\enigma.js:3119:37)
    at Session.send (C:\Users\anders.uddenberg\Desktop\spotifySessionApp2\node_modules\enigma.js\dist\enigma.js:1569:32)
    at Object.fn [as getActiveDoc] (C:\Users\anders.uddenberg\Desktop\spotifySessionApp2\node_modules\enigma.js\dist\enigma.js:2776:32)
    at qix.global.createSessionApp.then (C:\Users\anders.uddenberg\Desktop\spotifySessionApp2\engine.js:178:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Not connected
    at RPC.send (C:\Users\anders.uddenberg\Desktop\spotifySessionApp2\node_modules\enigma.js\dist\enigma.js:3119:37)
    at Session.send (C:\Users\anders.uddenberg\Desktop\spotifySessionApp2\node_modules\enigma.js\dist\enigma.js:1569:32)
    at Object.fn [as getActiveDoc] (C:\Users\anders.uddenberg\Desktop\spotifySessionApp2\node_modules\enigma.js\dist\enigma.js:2776:32)
    at qix.global.createSessionApp.then (C:\Users\anders.uddenberg\Desktop\spotifySessionApp2\engine.js:178:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by ludberg** [comment]
Could it be a certificate issue?

**Comment by ludberg** [comment]
What's the emptyAppID and directory below? Should I do something in the QMC with them?

` emptyAppID:"82df6f83-a835-4587-ab8f-76c20155dbfc",
    hostname:'localhost',
    cookieName: 'X-sess',
    directory:'CUSTOM',
	prefix:'/ano/',`

**Comment by ludberg** [comment]
I found the solution. I needed a Access Rule and allocate a token to the user. 

Now I'm stuck on these erors:

`446	11.34.2.0	20180224T122759.761+0100	WARN	ex188	793dfac1-f4ab-4440-a135-4664d5a294c8	Command=Open connection;Result=-2146233079;ResultText=Error: Fjärrservern returnerade ett fel: (404) Kunde inte hittas.	0	0	0	INTERNAL	sa_proxy	0	Not available	Proxy	Not available	Not available	Open connection	-2146233079	Web exception: Protocol error: Response stream exists. Remote endpoint 'http://localhost:3002/main'	793dfac1-f4ab-4440-a135-4664d5a294c8`

![image](https://user-images.githubusercontent.com/3208326/36629783-46da639a-195b-11e8-858e-983979ba340a.png)

**Comment by ludberg** [comment]
Here's a quick update. 
Apparently there is a hard-coded ClientId (spotify) in line 84 of public/login.html. 
This is your client id :)

Once I changed this to my Spotify Client id I get this error: 
```
Request URL:http://ex188:4248/windows_authentication/?targetId=d648cbad-bb96-4002-be7e-2623655933c2
Request Method:GET
Status Code:400 Bad request: Couldn't find virtual proxy derived from targetId d648cbad-bb96-4002-be7e-2623655933c2
Remote Address:192.168.100.141:4248
```

**Comment by aalteirac** [comment]
Hi, 
A lot of different things :-) If you remove the session module you won't be authenticated, or wrongly authenticated for my logic. The session endpoint is not for direct access (requires a cookie otherwise raises 500)
The empty app guid doesn't need to be changed, no app or QMC settings needed. 
My client ID is indeed in the login ;-) forgot to remove but it's not secret, no worries.
I think your problem comes from the session module and cookie creation. You're doing a lot of tests but I'm missing the context when some errors happen, really hard to try to reproduce on my side. 
The only thing I can propose to help is a live debugging session over webex, otherwise I'm afraid it will be hard. Please ping me by email and I will arrange.

Thanks
